In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("general_data.csv")

In [3]:
df

Age Attrition     BusinessTravel              Department  \
0      51        No      Travel_Rarely                   Sales   
1      31       Yes  Travel_Frequently  Research & Development   
2      32        No  Travel_Frequently  Research & Development   
3      38        No         Non-Travel  Research & Development   
4      32        No      Travel_Rarely  Research & Development   
...   ...       ...                ...                     ...   
4405   42        No      Travel_Rarely  Research & Development   
4406   29        No      Travel_Rarely  Research & Development   
4407   25        No      Travel_Rarely  Research & Development   
4408   42        No      Travel_Rarely                   Sales   
4409   40        No      Travel_Rarely  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  EmployeeID  \
0                    6          2  Life Sciences              1           1   
1                   10          1  Life Sciences              1           2   
2                   17          4          Other              1           3   
3                    2          5  Life Sciences              1           4   
4                   10          1        Medical              1           5   
...                ...        ...            ...            ...         ...   
4405                 5          4        Medical              1        4406   
4406                 2          4        Medical              1        4407   
4407                25          2  Life Sciences              1        4408   
4408                18          2        Medical              1        4409   
4409                28          3        Medical              1        4410   

      Gender  ...  NumCompaniesWorked Over18 PercentSalaryHike  StandardHours  \
0     Female  ...                 1.0      Y                11              8   
1     Female  ...                 0.0      Y                23              8   
2       Male  ...                 1.0      Y                15              8   
3       Male  ...                 3.0      Y                11              8   
4       Male  ...                 4.0      Y                12              8   
...      ...  ...                 ...    ...               ...            ...   
4405  Female  ...                 3.0      Y                17              8   
4406    Male  ...                 2.0      Y                15              8   
4407    Male  ...                 0.0      Y                20              8   
4408    Male  ...                 0.0      Y                14              8   
4409    Male  ...                 0.0      Y                12              8   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    0               1.0                      6   
1                    1               6.0                      3   
2                    3               5.0                      2   
3                    3              13.0                      5   
4                    2               9.0                      2   
...                ...               ...                    ...   
4405                 1              10.0                      5   
4406                 0              10.0                      2   
4407                 0               5.0                      4   
4408                 1              10.0                      2   
4409                 0               NaN                      6   

      YearsAtCompany  YearsSinceLastPromotion  YearsWithCurrManager  
0                  1                        0                     0  
1                  5                        1                     4  
2                  5                        0                     3  
3                  8                        7                     5  
4                  6                        0                     4  
...              ...                      ...                   ..

In [4]:
df1=pd.get_dummies(data=df,drop_first=True)

In [5]:
df1.isnull().sum()

Age                                   0
DistanceFromHome                      0
Education                             0
EmployeeCount                         0
EmployeeID                            0
JobLevel                              0
MonthlyIncome                         0
NumCompaniesWorked                   19
PercentSalaryHike                     0
StandardHours                         0
StockOptionLevel                      0
TotalWorkingYears                     9
TrainingTimesLastYear                 0
YearsAtCompany                        0
YearsSinceLastPromotion               0
YearsWithCurrManager                  0
Attrition_Yes                         0
BusinessTravel_Travel_Frequently      0
BusinessTravel_Travel_Rarely          0
Department_Research & Development     0
Department_Sales                      0
EducationField_Life Sciences          0
EducationField_Marketing              0
EducationField_Medical                0
EducationField_Other                  0


In [6]:
df1.fillna(method='pad',inplace=True)

In [7]:
y=df1['Attrition_Yes']

In [8]:
df1.drop(['StandardHours','EmployeeCount','EmployeeID','Attrition_Yes'],axis=1,inplace=True)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test=train_test_split(df1,y,test_size=0.35,random_state=25)

In [11]:
from sklearn.linear_model import LogisticRegression 

In [12]:
model=LogisticRegression()
model.fit(X_train,y_train)


C:\Users\venka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
model.score(X_train,y_train)

0.8394975575715282

In [14]:
y_pred=model.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [16]:
confusion_matrix(y_test,y_pred)

array([[1293,    0],
       [ 251,    0]], dtype=int64)

In [17]:
accuracy_score(y_test,y_pred)

0.8374352331606217

In [18]:
model.coef_

array([[-2.59070477e-02, -3.76624566e-03, -1.93193988e-03,
        -9.53123573e-04, -3.70153309e-06,  7.30249246e-03,
        -1.42258463e-03, -1.17275753e-03, -2.37257678e-02,
        -4.26821833e-03, -1.83984498e-02,  1.03082921e-03,
        -1.64915977e-02,  1.83763784e-03, -1.48909012e-03,
        -5.14119534e-04, -5.37191078e-04,  2.55830796e-05,
        -4.44044309e-04,  3.90407193e-05, -1.78688271e-04,
        -3.58360444e-04, -3.46084469e-04, -8.91730634e-05,
         1.52161058e-04, -2.46544910e-04, -5.86454680e-04,
         4.86723144e-04,  1.73430815e-04, -1.78975508e-04,
        -2.19176436e-04, -2.00042757e-03,  3.04705640e-03]])

Above model is unable to predict True Negatives so using statsmodels.api we will find the important features required for the model

In [19]:
import statsmodels.api as sm

In [20]:
X1=sm.add_constant(df1)

C:\Users\venka\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [21]:
model=sm.Logit(y,X1)

In [22]:
result=model.fit()

Optimization terminated successfully.
         Current function value: inf
         Iterations 7


C:\Users\venka\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1789: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


In [23]:
result.summary()

C:\Users\venka\Anaconda3\lib\site-packages\statsmodels\base\model.py:492: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)
C:\Users\venka\Anaconda3\lib\site-packages\statsmodels\base\model.py:492: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:          Attrition_Yes   No. Observations:                 4410
Model:                          Logit   Df Residuals:                     4376
Method:                           MLE   Df Model:                           33
Date:                Wed, 12 Aug 2020   Pseudo R-squ.:                     inf
Time:                        14:06:59   Log-Likelihood:                   -inf
converged:                       True   LL-Null:                        0.0000
Covariance Type:            nonrobust   LLR p-value:                     1.000
=====================================================================================================
                                        coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 0.0845      0.508      0.166      0.868      -0.910       1.079
Age                                  -0.0307      0.007     -4.379      0.000      -0.044      -0.017
DistanceFromHome                     -0.0020      0.006     -0.358      0.721      -0.013       0.009
Education                            -0.0585      0.044     -1.329      0.184      -0.145       0.028
JobLevel                             -0.0275      0.041     -0.676      0.499      -0.107       0.052
MonthlyIncome                     -9.845e-07   9.71e-07     -1.014      0.311   -2.89e-06    9.19e-07
NumCompaniesWorked                    0.1308      0.019      6.886      0.000       0.094       0.168
PercentSalaryHike                     0.0192      0.012      1.579      0.114      -0.005       0.043
StockOptionLevel                     -0.0939      0.053     -1.761      0.078      -0.198       0.011
TotalWorkingYears                    -0.0623      0.012     -5.069      0.000      -0.086      -0.038
TrainingTimesLastYear                -0.1443      0.036     -3.968      0.000      -0.216      -0.073
YearsAtCompany                        0.0151      0.019      0.802      0.423      -0.022       0.052
YearsSinceLastPromotion               0.1398      0.021      6.679      0.000       0.099       0.181
YearsWithCurrManager                 -0.1451      0.023     -6.296      0.000      -0.190      -0.100
BusinessTravel_Travel_Frequently      1.4716      0.202      7.273      0.000       1.075       1.868
BusinessTravel_Travel_Rarely          0.7349      0.190      3.865      0.000       0.362       1.108
Department_Research & Development    -0.5258      0.256     -2.055      0.040      -1.027      -0.024
Department_Sales                     -0.6692      0.269     -2.485      0.013      -1.197      -0.141
EducationField_Life Sciences         -0.6826      0.358     -1.908      0.056      -1.384       0.019
EducationField_Marketing             -0.7669      0.392     -1.955      0.051      -1.536       0.002
EducationField_Medical               -0.7477      0.359     -2.081      0.037      -1.452      -0.044
EducationField_Other                 -1.0186      0.405     -2.512      0.012      -1.813      -0.224
EducationField_Technical Degree      -1.0378      0.386     -2.686      0.007      -1.795      -0.280
Gender_Male                           0.0883      0.092      0.961      0.337      -0.092       0.268
JobRole_Human Resources              -0.0997      0.289     -0.345      0.730      -0.666       0.467
JobRole_Laboratory Technician         0.1532      0.186      0.822      0.411      -0.212       0.519
JobRole_Manager                      -0.2277      0.235     -0.968      0.333      -0.689       0.234
JobRole_Manufacturing Director       -0.4548      0.224     -2.032      0.042      -0.894      -0.016
JobRole_Research Director             0.5510      0.226      2.439      0.015  

Features whose p-value is greater than 0.05, needs to be removed and create a model

In [24]:
df1.drop(['MaritalStatus_Married','JobRole_Sales Representative','JobRole_Sales Executive','JobRole_Research Scientist','JobRole_Manager','JobRole_Laboratory Technician','JobRole_Human Resources','Gender_Male','YearsAtCompany','StockOptionLevel','DistanceFromHome','PercentSalaryHike','MonthlyIncome','JobLevel','Education'],axis=1,inplace=True)

In [25]:
df1

Age  NumCompaniesWorked  TotalWorkingYears  TrainingTimesLastYear  \
0      51                 1.0                1.0                      6   
1      31                 0.0                6.0                      3   
2      32                 1.0                5.0                      2   
3      38                 3.0               13.0                      5   
4      32                 4.0                9.0                      2   
...   ...                 ...                ...                    ...   
4405   42                 3.0               10.0                      5   
4406   29                 2.0               10.0                      2   
4407   25                 0.0                5.0                      4   
4408   42                 0.0               10.0                      2   
4409   40                 0.0               10.0                      6   

      YearsSinceLastPromotion  YearsWithCurrManager  \
0                           0                     0   
1                           1                     4   
2                           0                     3   
3                           7                     5   
4                           0                     4   
...                       ...                   ...   
4405                        0                     2   
4406                        0                     2   
4407                        1                     2   
4408                        7                     8   
4409                        3                     9   

      BusinessTravel_Travel_Frequently  BusinessTravel_Travel_Rarely  \
0                                    0                             1   
1                                    1                             0   
2                                    1                             0   
3                                    0                             0   
4                                    0                             1   
...                                ...                           ...   
4405                                 0                             1   
4406                                 0                             1   
4407                                 0                             1   
4408                                 0                             1   
4409                                 0                             1   

      Department_Research & Development  Department_Sales  \
0                                     0                 1   
1                                     1                 0   
2                                     1                 0   
3                                     1                 0   
4                                     1                 0   
...                                 ...               ...   
4405                                  1                 0   
4406                                  1                 0   
4407                                  1                 0   
4408                                  0                 1   
4409                                  1                 0   

      EducationField_Life Sciences  EducationField_Marketing  \
0                                1                         0   
1                                1                         0   
2                                0                         0   
3                                1                         0   
4                                0                         0   
...                            ...                       ...   
4405                             0                         0   
4406                             0                         0   
4407                             1                         0   
4408                             0                         0   
4409                             0                         0   

      EducationField_Medical  EducationField_Other  \
0                      

In [26]:
X1_train,X1_test,y1_train,y1_test=train_test_split(df1,y,test_size=0.35,random_state=25)

In [27]:
model1=LogisticRegression()
model1.fit(X1_train,y1_train)


C:\Users\venka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
model1.score(X1_train,y1_train)

0.8475226796929518

In [29]:
y1_pred=model1.predict(X1_test)

In [30]:
confusion_matrix(y1_test,y1_pred)

array([[1284,    9],
       [ 229,   22]], dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
accuracy_score(y1_test,y1_pred)

0.8458549222797928

In [36]:
X2=sm.add_constant(df1)
model_sm=sm.Logit(y,X2)
result_sm=model_sm.fit()

C:\Users\venka\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)
C:\Users\venka\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1789: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


Optimization terminated successfully.
         Current function value: inf
         Iterations 7


In [37]:
result_sm.summary()

C:\Users\venka\Anaconda3\lib\site-packages\statsmodels\base\model.py:492: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)
C:\Users\venka\Anaconda3\lib\site-packages\statsmodels\base\model.py:492: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:          Attrition_Yes   No. Observations:                 4410
Model:                          Logit   Df Residuals:                     4391
Method:                           MLE   Df Model:                           18
Date:                Wed, 12 Aug 2020   Pseudo R-squ.:                     inf
Time:                        14:10:10   Log-Likelihood:                   -inf
converged:                       True   LL-Null:                        0.0000
Covariance Type:            nonrobust   LLR p-value:                     1.000
=====================================================================================================
                                        coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 0.3077      0.377      0.817      0.414      -0.431       1.046
Age                                  -0.0292      0.007     -4.244      0.000      -0.043      -0.016
NumCompaniesWorked                    0.1249      0.018      6.812      0.000       0.089       0.161
TotalWorkingYears                    -0.0600      0.011     -5.523      0.000      -0.081      -0.039
TrainingTimesLastYear                -0.1421      0.036     -3.949      0.000      -0.213      -0.072
YearsSinceLastPromotion               0.1432      0.019      7.662      0.000       0.107       0.180
YearsWithCurrManager                 -0.1308      0.019     -6.894      0.000      -0.168      -0.094
BusinessTravel_Travel_Frequently      1.4666      0.200      7.322      0.000       1.074       1.859
BusinessTravel_Travel_Rarely          0.7194      0.188      3.824      0.000       0.351       1.088
Department_Research & Development    -0.5616      0.253     -2.223      0.026      -1.057      -0.066
Department_Sales                     -0.7163      0.267     -2.687      0.007      -1.239      -0.194
EducationField_Life Sciences         -0.6356      0.353     -1.801      0.072      -1.327       0.056
EducationField_Marketing             -0.6913      0.387     -1.786      0.074      -1.450       0.067
EducationField_Medical               -0.7038      0.354     -1.987      0.047      -1.398      -0.010
EducationField_Other                 -0.9923      0.398     -2.493      0.013      -1.773      -0.212
EducationField_Technical Degree      -0.9790      0.381     -2.567      0.010      -1.727      -0.231
JobRole_Manufacturing Director       -0.6076      0.169     -3.598      0.000      -0.939      -0.277
JobRole_Research Director             0.4051      0.171      2.363      0.018       0.069       0.741
MaritalStatus_Single                  0.8637      0.090      9.635      0.000       0.688       1.039
=====================================================================================================
"""

In [42]:
print(" After removing fetaures whose p-value is greater than 0.05 we are able predict True Negatives as well. First confusion matrix has zero True negatives whereas second confusion matrix has 12 True Negatives") 
print("First confusion matrix \n",confusion_matrix(y_test,y_pred))
print("Second confusion matrix \n",confusion_matrix(y1_test,y1_pred))

 After removing fetaures whose p-value is greater than 0.05 we are able predict True Negatives as well. First confusion matrix has zero True negatives whereas second confusion matrix has 12 True Negatives
First confusion matrix 
 [[1293    0]
 [ 251    0]]
Second confusion matrix 
 [[1284    9]
 [ 229   22]]
