In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel("Bank_Personal_Loan_Modelling.xlsx",sheet_name=1)

In [3]:
Y=df['Personal Loan']

In [4]:
df.drop(['ZIP Code','ID','Personal Loan'],axis=1,inplace=True)

In [5]:
Y.shape

(5000,)

In [6]:
from sklearn.linear_model import LogisticRegression 

In [7]:
model=LogisticRegression()

In [8]:
model.fit(df,Y)

C:\Users\venka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
y_pred=model.predict(df)

In [10]:
from sklearn.metrics import confusion_matrix

In [11]:
confusion_matrix(Y,y_pred)

array([[4456,   64],
       [ 184,  296]], dtype=int64)

In [12]:
model.coef_

array([[-3.78477924e-01,  3.81791155e-01,  5.09313326e-02,
         6.29837631e-01,  1.12640852e-01,  1.67382029e+00,
         5.59720552e-04, -7.75307121e-01,  3.37955039e+00,
        -6.28837830e-01, -9.91561454e-01]])

In [13]:
model.intercept_

array([-3.12788703])

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy_score(Y,y_pred)

0.9504

In [16]:
import statsmodels.api as sm

In [17]:
X1=sm.add_constant(df)

C:\Users\venka\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [18]:
model=sm.Logit(Y,X1)

In [19]:
result=model.fit()

Optimization terminated successfully.
         Current function value: 0.128435
         Iterations 9


In [20]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:          Personal Loan   No. Observations:                 5000
Model:                          Logit   Df Residuals:                     4988
Method:                           MLE   Df Model:                           11
Date:                Wed, 12 Aug 2020   Pseudo R-squ.:                  0.5938
Time:                        14:31:22   Log-Likelihood:                -642.18
converged:                       True   LL-Null:                       -1581.0
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                -12.1928      1.645     -7.411      0.000     -15.417      -8.968
Age                   -0.0536      0.061     -0.874      0.382      -0.174       0.067
Experience             0.0638      0.061      1.046      0.295      -0.056       0.183
Income                 0.0546      0.003     20.831      0.000       0.049       0.060
Family                 0.6958      0.074      9.364      0.000       0.550       0.841
CCAvg                  0.1240      0.040      3.127      0.002       0.046       0.202
Education              1.7362      0.115     15.088      0.000       1.511       1.962
Mortgage               0.0005      0.001      0.856      0.392      -0.001       0.002
Securities Account    -0.9368      0.286     -3.277      0.001      -1.497      -0.377
CD Account             3.8225      0.324     11.800      0.000       3.188       4.457
Online                -0.6752      0.157     -4.298      0.000      -0.983      -0.367
CreditCard            -1.1197      0.205     -5.462      0.000      -1.522      -0.718
======================================================================================
"""

Features whose p-value is greater than 0.05, needs to be removed and create a model

In [21]:
df.drop(['Age','Experience','Mortgage'],axis=1,inplace=True)

In [22]:
model1=LogisticRegression()

In [24]:
model1.fit(df,Y)

C:\Users\venka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
y1_pred=model1.predict(df)
confusion_matrix(Y,y1_pred)

array([[4466,   54],
       [ 187,  293]], dtype=int64)

In [26]:
accuracy_score(Y,y1_pred)

0.9518

In [27]:
X2=sm.add_constant(df)

C:\Users\venka\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


In [28]:
model=sm.Logit(Y,X2)

In [29]:
result=model.fit()

Optimization terminated successfully.
         Current function value: 0.128862
         Iterations 9


In [30]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:          Personal Loan   No. Observations:                 5000
Model:                          Logit   Df Residuals:                     4991
Method:                           MLE   Df Model:                            8
Date:                Wed, 12 Aug 2020   Pseudo R-squ.:                  0.5925
Time:                        14:31:45   Log-Likelihood:                -644.31
converged:                       True   LL-Null:                       -1581.0
Covariance Type:            nonrobust   LLR p-value:                     0.000
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                -13.2242      0.562    -23.510      0.000     -14.327     -12.122
Income                 0.0547      0.003     21.133      0.000       0.050       0.060
Family                 0.6904      0.074      9.304      0.000       0.545       0.836
CCAvg                  0.1137      0.039      2.896      0.004       0.037       0.191
Education              1.7041      0.112     15.162      0.000       1.484       1.924
Securities Account    -0.9346      0.285     -3.281      0.001      -1.493      -0.376
CD Account             3.8533      0.323     11.913      0.000       3.219       4.487
Online                -0.6675      0.157     -4.259      0.000      -0.975      -0.360
CreditCard            -1.1237      0.205     -5.481      0.000      -1.525      -0.722
======================================================================================
"""