In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.drop(['Cabin','PassengerId','Name','Ticket','Embarked'],axis=1,inplace=True)

In [4]:
df['Sex']=np.where(df['Sex']=='male',1,0)

In [5]:
df

Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0           0       3    1  22.0      1      0   7.2500
1           1       1    0  38.0      1      0  71.2833
2           1       3    0  26.0      0      0   7.9250
3           1       1    0  35.0      1      0  53.1000
4           0       3    1  35.0      0      0   8.0500
..        ...     ...  ...   ...    ...    ...      ...
884         0       2    1  27.0      0      0  13.0000
885         1       1    0  19.0      0      0  30.0000
886         0       3    0  45.0      1      2  23.4500
887         1       1    1  26.0      0      0  30.0000
888         0       3    1  32.0      0      0   7.7500

[889 rows x 7 columns]

In [6]:
features=['Survived','Pclass','SibSp','Parch','Sex']

In [7]:
def supportvectorclassifier(features,df):
    accuracy=[]
    for feature in features:
        from sklearn.metrics import accuracy_score,confusion_matrix
        from sklearn.svm import SVC
        from sklearn.model_selection import train_test_split
        model=SVC(gamma=0.01,C=100)
        Dv=df[feature]
        X=df.drop([feature],axis=1)
        Xtrain,Xtest,ytrain,ytest=train_test_split(X,Dv,test_size=0.25)
        model.fit(Xtrain,ytrain)
        ypred=model.predict(Xtest)
        t=accuracy_score(ytest,ypred)
        print("Accuracy score of the model when is dependent feature is",feature," :",t)
        accuracy.append(t)
        print("Confusion matrix when dependent feature is:",feature)
        print(confusion_matrix(ytest,ypred))
    return accuracy
    

In [8]:
accuracy=supportvectorclassifier(features,df)

Accuracy score of the model when is dependent feature is Survived  : 0.8026905829596412
Confusion matrix when dependent feature is: Survived
[[119  25]
 [ 19  60]]
Accuracy score of the model when is dependent feature is Pclass  : 0.8968609865470852
Confusion matrix when dependent feature is: Pclass
[[ 49   4   0]
 [  5  34   8]
 [  2   4 117]]
Accuracy score of the model when is dependent feature is SibSp  : 0.8026905829596412
Confusion matrix when dependent feature is: SibSp
[[145  11   0   1   0   0   0]
 [ 16  26   2   2   0   0   0]
 [  2   5   0   2   1   0   0]
 [  0   2   0   1   0   0   0]
 [  0   0   0   0   4   0   0]
 [  0   0   0   0   0   2   0]
 [  0   0   0   0   0   0   1]]
Accuracy score of the model when is dependent feature is Parch  : 0.8340807174887892
Confusion matrix when dependent feature is: Parch
[[166   9   7   0   0   0]
 [ 12  10   2   0   0   0]
 [  2   3  10   0   0   0]
 [  0   0   1   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   1   0]]
Ac

In [9]:
a=pd.DataFrame([features,accuracy],index=['Independent Variable','Model Accuracy']).T

In [10]:
a


Independent Variable Model Accuracy
0             Survived       0.802691
1               Pclass       0.896861
2                SibSp       0.802691
3                Parch       0.834081
4                  Sex       0.672646