In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
884          887         0       2   
885          888         1       1   
886          889         0       3   
887          890         1       1   
888          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
884                              Montvila, Rev. Juozas    male  27.0      0   
885                       Graham, Miss. Margaret Edith  female  19.0      0   
886           Johnston, Miss. Catherine Helen "Carrie"  female  45.0      1   
887                              Behr, Mr. Karl Howell    male  26.0      0   
888                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
884      0            211536  13.0000   NaN        S  
885      0            112053  30.0000   B42        S  
886      2        W./C. 6607  23.4500   NaN        S  
887      0            111369  30.0000  C148        C  
888      0            370376   7.7500   NaN        Q  

[889 rows x 12 columns]

In [4]:
df.drop(['Cabin','PassengerId','Name','Ticket'],axis=1,inplace=True)

In [5]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
884         0       2    male  27.0      0      0  13.0000        S
885         1       1  female  19.0      0      0  30.0000        S
886         0       3  female  45.0      1      2  23.4500        S
887         1       1    male  26.0      0      0  30.0000        C
888         0       3    male  32.0      0      0   7.7500        Q

[889 rows x 8 columns]

In [6]:
a=pd.get_dummies(df[['Embarked','Sex']])

In [7]:
df=pd.concat([df,a],axis=1)

In [8]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  \
0           0       3    male  22.0      1      0   7.2500        S   
1           1       1  female  38.0      1      0  71.2833        C   
2           1       3  female  26.0      0      0   7.9250        S   
3           1       1  female  35.0      1      0  53.1000        S   
4           0       3    male  35.0      0      0   8.0500        S   
..        ...     ...     ...   ...    ...    ...      ...      ...   
884         0       2    male  27.0      0      0  13.0000        S   
885         1       1  female  19.0      0      0  30.0000        S   
886         0       3  female  45.0      1      2  23.4500        S   
887         1       1    male  26.0      0      0  30.0000        C   
888         0       3    male  32.0      0      0   7.7500        Q   

     Embarked_C  Embarked_Q  Embarked_S  Sex_female  Sex_male  
0             0           0           1           0         1  
1             1           0           0           1         0  
2             0           0           1           1         0  
3             0           0           1           1         0  
4             0           0           1           0         1  
..          ...         ...         ...         ...       ...  
884           0           0           1           0         1  
885           0           0           1           1         0  
886           0           0           1           1         0  
887           1           0           0           0         1  
888           0           1           0           0         1  

[889 rows x 13 columns]

In [9]:
df.drop(['Sex','Embarked'],axis=1,inplace=True)

In [10]:
df

Survived  Pclass   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  \
0           0       3  22.0      1      0   7.2500           0           0   
1           1       1  38.0      1      0  71.2833           1           0   
2           1       3  26.0      0      0   7.9250           0           0   
3           1       1  35.0      1      0  53.1000           0           0   
4           0       3  35.0      0      0   8.0500           0           0   
..        ...     ...   ...    ...    ...      ...         ...         ...   
884         0       2  27.0      0      0  13.0000           0           0   
885         1       1  19.0      0      0  30.0000           0           0   
886         0       3  45.0      1      2  23.4500           0           0   
887         1       1  26.0      0      0  30.0000           1           0   
888         0       3  32.0      0      0   7.7500           0           1   

     Embarked_S  Sex_female  Sex_male  
0             1           0         1  
1             0           1         0  
2             1           1         0  
3             1           1         0  
4             1           0         1  
..          ...         ...       ...  
884           1           0         1  
885           1           1         0  
886           1           1         0  
887           0           0         1  
888           0           0         1  

[889 rows x 11 columns]

In [11]:
Dv=df['Survived']
df.drop(['Survived'],axis=1,inplace=True)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest=train_test_split(df,Dv,test_size=0.25)

In [14]:
model=KNeighborsClassifier()

In [15]:
accuracy=[0]
from sklearn.metrics import accuracy_score,confusion_matrix

In [16]:
for i in range(1,len(Xtrain)):
    model=KNeighborsClassifier(n_neighbors=i)
    model.fit(Xtrain,ytrain)
    ypred=model.predict(Xtest)
    t=accuracy_score(ytest,ypred)
    print('Accuracy score of the model is ',t)
    accuracy.append(t)
    print("Confusion matrix when n_neidbhors is:",i)
    print(confusion_matrix(ytest,ypred))
    

Accuracy score of the model is  0.6771300448430493
Confusion matrix when n_neidbhors is: 1
[[100  31]
 [ 41  51]]
Accuracy score of the model is  0.695067264573991
Confusion matrix when n_neidbhors is: 2
[[119  12]
 [ 56  36]]
Accuracy score of the model is  0.7174887892376681
Confusion matrix when n_neidbhors is: 3
[[107  24]
 [ 39  53]]
Accuracy score of the model is  0.6681614349775785
Confusion matrix when n_neidbhors is: 4
[[110  21]
 [ 53  39]]
Accuracy score of the model is  0.6860986547085202
Confusion matrix when n_neidbhors is: 5
[[104  27]
 [ 43  49]]
Accuracy score of the model is  0.7085201793721974
Confusion matrix when n_neidbhors is: 6
[[116  15]
 [ 50  42]]
Accuracy score of the model is  0.6905829596412556
Confusion matrix when n_neidbhors is: 7
[[108  23]
 [ 46  46]]
Accuracy score of the model is  0.672645739910314
Confusion matrix when n_neidbhors is: 8
[[116  15]
 [ 58  34]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 9

Confusion matrix when n_neidbhors is: 80
[[117  14]
 [ 58  34]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 81
[[117  14]
 [ 57  35]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 82
[[117  14]
 [ 57  35]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 83
[[117  14]
 [ 57  35]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 84
[[117  14]
 [ 57  35]]
Accuracy score of the model is  0.6860986547085202
Confusion matrix when n_neidbhors is: 85
[[117  14]
 [ 56  36]]
Accuracy score of the model is  0.6905829596412556
Confusion matrix when n_neidbhors is: 86
[[118  13]
 [ 56  36]]
Accuracy score of the model is  0.6860986547085202
Confusion matrix when n_neidbhors is: 87
[[117  14]
 [ 56  36]]
Accuracy score of the model is  0.6905829596412556
Confusion matrix when n_neidbhors is: 88
[[118  13]
 [ 56  36]]
Accuracy score o

Accuracy score of the model is  0.6771300448430493
Confusion matrix when n_neidbhors is: 158
[[124   7]
 [ 65  27]]
Accuracy score of the model is  0.6771300448430493
Confusion matrix when n_neidbhors is: 159
[[124   7]
 [ 65  27]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 160
[[125   6]
 [ 65  27]]
Accuracy score of the model is  0.6771300448430493
Confusion matrix when n_neidbhors is: 161
[[124   7]
 [ 65  27]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 162
[[125   6]
 [ 65  27]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 163
[[125   6]
 [ 65  27]]
Accuracy score of the model is  0.6771300448430493
Confusion matrix when n_neidbhors is: 164
[[125   6]
 [ 66  26]]
Accuracy score of the model is  0.6816143497757847
Confusion matrix when n_neidbhors is: 165
[[125   6]
 [ 65  27]]
Accuracy score of the model is  0.6771300448430493
Confusion matrix when

[[128   3]
 [ 76  16]]
Accuracy score of the model is  0.6591928251121076
Confusion matrix when n_neidbhors is: 237
[[128   3]
 [ 73  19]]
Accuracy score of the model is  0.6547085201793722
Confusion matrix when n_neidbhors is: 238
[[128   3]
 [ 74  18]]
Accuracy score of the model is  0.6636771300448431
Confusion matrix when n_neidbhors is: 239
[[128   3]
 [ 72  20]]
Accuracy score of the model is  0.6502242152466368
Confusion matrix when n_neidbhors is: 240
[[128   3]
 [ 75  17]]
Accuracy score of the model is  0.6591928251121076
Confusion matrix when n_neidbhors is: 241
[[128   3]
 [ 73  19]]
Accuracy score of the model is  0.6457399103139013
Confusion matrix when n_neidbhors is: 242
[[128   3]
 [ 76  16]]
Accuracy score of the model is  0.6502242152466368
Confusion matrix when n_neidbhors is: 243
[[128   3]
 [ 75  17]]
Accuracy score of the model is  0.6412556053811659
Confusion matrix when n_neidbhors is: 244
[[128   3]
 [ 77  15]]
Accuracy score of the model is  0.650224215246636

[[131   0]
 [ 91   1]]
Accuracy score of the model is  0.5919282511210763
Confusion matrix when n_neidbhors is: 315
[[131   0]
 [ 91   1]]
Accuracy score of the model is  0.5919282511210763
Confusion matrix when n_neidbhors is: 316
[[131   0]
 [ 91   1]]
Accuracy score of the model is  0.5919282511210763
Confusion matrix when n_neidbhors is: 317
[[131   0]
 [ 91   1]]
Accuracy score of the model is  0.5919282511210763
Confusion matrix when n_neidbhors is: 318
[[131   0]
 [ 91   1]]
Accuracy score of the model is  0.5919282511210763
Confusion matrix when n_neidbhors is: 319
[[131   0]
 [ 91   1]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 320
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 321
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 322
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.591928251121076

[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 387
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 388
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 389
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 390
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 391
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 392
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 393
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 394
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.587443946188340

Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 465
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 466
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 467
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 468
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 469
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 470
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 471
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 472
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when

Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 539
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 540
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 541
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 542
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 543
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 544
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 545
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 546
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when

[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 616
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 617
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 618
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 619
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 620
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 621
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 622
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.5874439461883408
Confusion matrix when n_neidbhors is: 623
[[131   0]
 [ 92   0]]
Accuracy score of the model is  0.587443946188340

In [17]:
max=accuracy[0]
index=0

In [18]:
for i in range(len(accuracy)):
    if max<accuracy[i]:
        max=accuracy[i]
        index=i

In [19]:
print("Best K-nearest neighbor value is ", index)

Best K-nearest neighbor value is  25
