# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.24032598 0.39169011 0.76365719]
  [0.56661695 0.2952317  0.23315783]
  [0.19123173 0.96634135 0.46991819]]

 [[0.1832582  0.80109332 0.39585415]
  [0.77582521 0.14920149 0.8008504 ]
  [0.23998988 0.83068719 0.51834092]]

 [[0.30979117 0.77225348 0.57106476]
  [0.67671305 0.77170689 0.88091594]
  [0.5836436  0.46862381 0.42228528]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
k = np.diag(1+np.arange(4),k=-1)

print(k)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
c = np.zeros((8,8),dtype=int)

c[1::2,::2] = 1

c[::2,1::2] = 1

print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
arr = np.random.random((3,3))
print(arr)
arrmax, arrmin = arr.max(), arr.min()
narr = (arr - arrmin)/(arrmax - arrmin)
print("After normalization:")
narr

[[0.06692204 0.73902463 0.63728856]
 [0.49525233 0.91108351 0.53373122]
 [0.29812315 0.23271616 0.87210975]]
After normalization:


array([[0.        , 0.79617777, 0.67566046],
       [0.50740327, 1.        , 0.55298566],
       [0.27388257, 0.19640096, 0.9538314 ]])

# 5.  How to find common values between two arrays?

In [5]:

a1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",a1)
a2 = [10, 30, 40]
print("Array2: ",a2)
print("Common values between two arrays:")
print(np.intersect1d(a1, a2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
if len(x) == len(y):
    i=0
    c=0
    while i<len(x):
        if x[i]==y[i]:
            c=c+1
            
        else:
            print("False")
            break
    if c == len(x):
        print("True")
else:
    print("False")
        
        

First array:
[1 1 0 1 0 1]
Second array:
[0 1 1 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
x = np.random.random(10)
print("Initial array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Initial array:
[0.50573877 0.80401322 0.07652003 0.25935607 0.41030992 0.79337159
 0.70703251 0.04697083 0.30737416 0.73340754]
Maximum value replaced by 0:
[0.50573877 0.         0.07652003 0.25935607 0.41030992 0.79337159
 0.70703251 0.04697083 0.30737416 0.73340754]


# 9. How to print all the values of an array?

In [9]:
n=np.zeros((4,4))
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
print("Original matrix:\n")
X = np.random.rand(5, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.00396594 0.09092719 0.52265615 0.78164866 0.3451848 ]
 [0.95919494 0.74113109 0.94353792 0.76521122 0.17701831]
 [0.22297541 0.66736149 0.42833318 0.44391617 0.29391417]
 [0.42290447 0.45234226 0.42480362 0.63652219 0.28886866]
 [0.08236933 0.61797118 0.4077609  0.41680501 0.48178022]]

Subtract the mean of each row of the said matrix:

[[-0.3449106  -0.25794936  0.1737796   0.43277211 -0.00369175]
 [ 0.24197624  0.0239124   0.22631922  0.04799252 -0.54020038]
 [-0.18832467  0.25606141  0.01703309  0.03261609 -0.11738592]
 [-0.02218377  0.00725402 -0.02028462  0.19143396 -0.15621958]
 [-0.318968    0.21663385  0.00642357  0.01546768  0.08044289]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
a=np.arange(0,12)
b=np.array([1,1,2,2,8,6,5,5,4,4])
l=[]
print("Before adding one at required index ")
print(a)
for i in b:
    if i not in l:
        l.append(i)
        a[i]=a[i]+1
print("After adding one at required index ")
print(a)


Before adding one at required index 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
After adding one at required index 
[ 0  2  3  3  5  6  7  7  9  9 10 11]


# 12.How to get the diagonal of a dot product?

In [12]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
res=np.dot(a,b)
print("Dot product of a and b")
print(res)
print("Diagonal elements of dot product")
np.diag(res)

Dot product of a and b
[[37 40]
 [85 92]]
Diagonal elements of dot product


array([37, 92])

# 13.How to find the most frequent value in an array?

In [13]:
a=np.array([1,1,2,6,2,4,6,4,5,6])
b=np.sort(a)
count=1
maxcount=0
l=[]
for i in b:
    if i in l:
        count=count+1
    l.append(i)
    if count > maxcount:
        maxcount=count
        value=i
print("Most frequent number",value)

    

Most frequent number 6


# 14.How to get the n largest values of an array

In [14]:
a=np.array([1,1,2,6,2,4,6,4,5,6])
b=np.sort(a)
n=int(input("Enter n value"))
l=[]
for i in b:
    if i not in l:
        l.append(i)
k=len(l)-n
print(n," Largest values in the array")
l[k:]

Enter n value2
2  Largest values in the array


[5, 6]

# 15.How to create a record array from a regular array?

In [15]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
