In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as st

In [2]:
df=pd.read_csv("general_data.csv")

In [4]:
df_Yes=df[df['Attrition']=="Yes"]
df_No=df[df['Attrition']=="No"]

In [5]:
df_Yes
df_No

Age Attrition     BusinessTravel              Department  \
0      51        No      Travel_Rarely                   Sales   
2      32        No  Travel_Frequently  Research & Development   
3      38        No         Non-Travel  Research & Development   
4      32        No      Travel_Rarely  Research & Development   
5      46        No      Travel_Rarely  Research & Development   
...   ...       ...                ...                     ...   
4405   42        No      Travel_Rarely  Research & Development   
4406   29        No      Travel_Rarely  Research & Development   
4407   25        No      Travel_Rarely  Research & Development   
4408   42        No      Travel_Rarely                   Sales   
4409   40        No      Travel_Rarely  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  EmployeeID  \
0                    6          2  Life Sciences              1           1   
2                   17          4          Other              1           3   
3                    2          5  Life Sciences              1           4   
4                   10          1        Medical              1           5   
5                    8          3  Life Sciences              1           6   
...                ...        ...            ...            ...         ...   
4405                 5          4        Medical              1        4406   
4406                 2          4        Medical              1        4407   
4407                25          2  Life Sciences              1        4408   
4408                18          2        Medical              1        4409   
4409                28          3        Medical              1        4410   

      Gender  ...  NumCompaniesWorked Over18 PercentSalaryHike  StandardHours  \
0     Female  ...                 1.0      Y                11              8   
2       Male  ...                 1.0      Y                15              8   
3       Male  ...                 3.0      Y                11              8   
4       Male  ...                 4.0      Y                12              8   
5     Female  ...                 3.0      Y                13              8   
...      ...  ...                 ...    ...               ...            ...   
4405  Female  ...                 3.0      Y                17              8   
4406    Male  ...                 2.0      Y                15              8   
4407    Male  ...                 0.0      Y                20              8   
4408    Male  ...                 0.0      Y                14              8   
4409    Male  ...                 0.0      Y                12              8   

      StockOptionLevel TotalWorkingYears  TrainingTimesLastYear  \
0                    0               1.0                      6   
2                    3               5.0                      2   
3                    3              13.0                      5   
4                    2               9.0                      2   
5                    0              28.0                      5   
...                ...               ...                    ...   
4405                 1              10.0                      5   
4406                 0              10.0                      2   
4407                 0               5.0                      4   
4408                 1              10.0                      2   
4409                 0               NaN                      6   

      YearsAtCompany  YearsSinceLastPromotion  YearsWithCurrManager  
0                  1                        0                     0  
2                  5                        0                     3  
3                  8                        7                     5  
4                  6                        0                     4  
5                  7                        7                     7  
...              ...                      ...                   ..

1. Wilcoxon test on DistanceFromHome and YearsAtCompany

In [7]:
stats,p=st.wilcoxon(df.DistanceFromHome,df.YearsAtCompany)
stats,p

(3204327.0, 1.4292401447645068e-37)

H0: There is no significant difference between DistanceFromHome and YearsAtCompany
H1: There is significant difference between DistanceFromHome and YearsAtCompany
As p value is lesser than 0.05, we reject H0 and accept H1

2. Friedman test on Education,MonthlyIncome and YearsAtCompany

In [8]:
stats,p=st.friedmanchisquare( df.Education,df.MonthlyIncome,df.YearsAtCompany)
stats,p

(7223.067546449037, 0.0)

H0: There is no significant difference between  Education,MonthlyIncome and YearsAtCompany
H1: There is significant difference between  Education,MonthlyIncome and YearsAtCompany
As p value is lesser than 0.05, we reject H0 and accept H1

3. Mann whitney test on two independent samples

In [10]:
stats,p=st.mannwhitneyu(df_Yes.YearsAtCompany,df_No.YearsAtCompany)
stats,p

(923238.0, 6.047598261692858e-37)

H0: There is no significant difference between YearsAtCompany in both cases
H1: There is significant difference between  YearsAtCompany in both cases
As p value is lesser than 0.05, we reject H0 and accept H1

In [ ]:
4. Kruskal-Wallis test

In [12]:
stats,p=st.kruskal(df[df['Education']==1]['MonthlyIncome'],df[df['Education']==2]['MonthlyIncome'],df[df['Education']==3]['MonthlyIncome'])
stats,p

(2.0301507609714973, 0.362375112790892)

H0: There is no significant difference between MonthlyIncome in different education levels
H1: There is significant difference between  MonthlyIncome in different education levels
As p value is greater than 0.05, we accept H0 

5. Chisquare test

In [30]:
dataset_table=pd.crosstab(df.Department,df.EducationField)

In [31]:
dataset_table.values 

array([[  81,   48,    0,   39,    9,   12],
       [   0, 1320,    0, 1089,  192,  282],
       [   0,  450,  477,  264,   45,  102]], dtype=int64)

In [33]:
stat, p, dof, expected = st.chi2_contingency(dataset_table)

In [34]:
stat, p, dof, expected

(3074.937741992298,
 0.0,
 10,
 array([[   3.47142857,   77.91428571,   20.44285714,   59.65714286,
           10.54285714,   16.97142857],
        [  52.95306122, 1188.50204082,  311.83469388,  910.00816327,
          160.82040816,  258.88163265],
        [  24.5755102 ,  551.58367347,  144.72244898,  422.33469388,
           74.63673469,  120.14693878]]))

In [36]:
prob = 0.95
critical = st.chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')
# interpret p-value
alpha = 1.0 - prob
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

probability=0.950, critical=18.307, stat=3074.938
Dependent (reject H0)
significance=0.050, p=0.000
Dependent (reject H0)


6.One-sample T-test

In [37]:
mean_population=df['MonthlyIncome'].mean()

In [38]:
mean_population

65029.31292517007

In [40]:
sample_size=100
MonthlyIncome_Sample=np.random.choice(df['MonthlyIncome'],sample_size)

In [41]:
MonthlyIncome_Sample

array([ 21090,  62090,  43450,  43190,  36330,  32800,  26700,  23050,
       106500,  33460,  71190,  97050,  23870,  76440, 165950, 118360,
       100960,  26600,  21190,  34520,  84740,  12000,  22320,  99800,
        23180,  86860,  26780,  21680, 187110,  58100,  31620,  48550,
        76370,  53760,  31800,  74460, 198330,  26420, 178750,  97560,
        50980, 175840,  32910,  48690,  68700,  35800,  30680,  43810,
        22960,  32120, 192720,  28100,  24510,  24300,  20330,  21680,
       103680,  45220,  54670,  40660,  25150,  21190,  24320,  29360,
       132120,  54820, 127420, 186650,  56470, 121690, 197400,  47170,
        51710,  34080, 104660,  55070,  35400,  27780, 137260,  40110,
        22670,  55620, 116910,  45810,  45070,  47770, 106090,  59140,
        33060,  20580,  64100,  26600,  63920,  60290,  17900,  16110,
        25660, 104750,  29500,  29720], dtype=int64)

In [43]:
stats,p_value=st.ttest_1samp(MonthlyIncome_Sample,mean_population)

In [44]:
stats,p_value

(-0.6266551280757375, 0.532327711784931)

In [45]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

we are accepting null hypothesis


There is no significant difference in the mean of sample and population

7. Two sample paired T Test

In [52]:
data=pd.read_excel("2. Paired Sample.xlsx",sheet_name=0)

In [53]:
data

ids  English   Math
0    43783    88.24  60.02
1    20278    89.45  70.19
2    20389    96.73  71.20
3    22820    74.06  55.89
4    24559    82.61  65.52
..     ...      ...    ...
393  34021    87.72  65.31
394  40697    91.01  70.25
395  34272    81.05  58.16
396  33628    75.59  66.84
397  39298    75.65  60.24

[398 rows x 3 columns]

In [55]:
stats,p=st.ttest_rel(data.English,data.Math)

In [56]:
stats,p

(36.312568981719856, 3.0710987192210606e-128)

In [57]:
if p < 0.05:   
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


There is  significant difference in the mean of sample and population

8. Two sample independent test

In [58]:
stats,p=st.ttest_ind(df_Yes.Age,df_No.Age)

In [59]:
stats,p

(-10.70661860061757, 1.9968016158894556e-26)

In [60]:
if p < 0.05:   
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

 we are rejecting null hypothesis


There is significant difference in the mean of two independent variables